# Generated by Django 5.1.4 on 2025-01-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_authenticationuser_managers'),
        ('control', '0003_spendingplan_spendingplanitens'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpenseItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('obs', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.PositiveSmallIntegerField()),
                ('amount_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dif_amount_paid', models.DecimalField(decimal_places=2, help_text='amount_sum field - amount_paid field', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type_expense', models.CharField(choices=[('F', 'FIXED'), ('V', 'VARIABLE')], default='F', max_length=1)),
                ('monthly_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.monthlyexpense')),
            ],
        ),
    ]
