# Generated by Django 5.1.4 on 2025-01-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_monthlyexpense_monthlyexpenseitens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpenseitens',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
