# Generated by Django 5.1.4 on 2025-01-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_monthlyexpenseitens_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyexpenseitens',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='monthlyexpenseitens',
            name='amount_sum',
        ),
        migrations.RemoveField(
            model_name='monthlyexpenseitens',
            name='dif_amount_paid',
        ),
        migrations.RemoveField(
            model_name='monthlyexpenseitens',
            name='is_active',
        ),
        migrations.AddField(
            model_name='monthlyexpenseitens',
            name='status',
            field=models.BooleanField(default=False, help_text='True = paid, False = not paid'),
        ),
        migrations.AlterField(
            model_name='monthlyexpenseitens',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
