# Generated by Django 5.1.4 on 2025-01-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_remove_monthlyexpenseitens_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyexpenseitens',
            old_name='status',
            new_name='is_paid',
        ),
    ]
