# Generated by Django 5.1.4 on 2025-01-13 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_rename_status_monthlyexpenseitens_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpenseItensHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('History', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.history')),
                ('monthly_expense_itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.monthlyexpenseitens')),
            ],
        ),
        migrations.CreateModel(
            name='SpendingPlanItensHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('History', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.history')),
                ('spending_plan_itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.spendingplanitens')),
            ],
        ),
        migrations.CreateModel(
            name='UserIncomeItensHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('History', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.history')),
                ('user_income_itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.userincomeitens')),
            ],
        ),
    ]
