# Generated by Django 5.1.4 on 2025-01-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_authenticationuser_managers'),
        ('control', '0009_rename_history_monthlyexpenseitenshistory_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveListItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.objectivelist')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveListItensHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.history')),
                ('objective_list_itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.objectivelistitens')),
            ],
        ),
    ]
