# Generated by Django 5.1.4 on 2025-01-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationuser',
            name='username',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
