# Generated by Django 5.1.4 on 2025-01-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_api_key_alter_user_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('U', 'USER'), ('A', 'API')], default='U', max_length=1),
        ),
    ]
