# Generated by Django 5.1.4 on 2025-01-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authenticationuser',
            managers=[
            ],
        ),
    ]
