# Generated by Django 5.1.4 on 2025-01-09 22:47

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_authenticationuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authenticationuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
